apiVersion: "kubeflow.org/v1alpha1"
kind: "TFJob"
metadata:
  name: "plate"
spec:
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: recolic/tfapp-plate:latest
              name: tensorflow
              resources:
                requests:
                  cpu: 100m
                  memory: 1200Mi
          restartPolicy: OnFailure
    - replicas: 1
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: recolic/tfapp-plate:latest
              name: tensorflow
              resources:
                requests:
                  cpu: 100m
                  memory: 1200Mi
          restartPolicy: OnFailure
    - replicas: 1
      tfReplicaType: PS
      template:
        spec:
          containers:
            - image: recolic/tfapp-plate:latest
              name: tensorflow
          restartPolicy: OnFailure
